### ISSUE TITLE
EPUB Zip header corrupted?

### ISSUE THREAD

**Issue by jeankaplansky** [benetech/AccessibleImageSampleBook#1]
Hi,

I attempted to download https://github.com/benetech/AccessibleImageSampleBook/blob/master/AccessibleImageSampleBook_v2.0.3.epub so I could look at the latest code.

Unfortunately all downloads give me a file with a corrupted .zip header - at least according to EPUBCHECK (Pagina): 

FATAL (PKG-004) FATAL_preposition "AccessibleImageSampleBook_v2.0.3.epub/AccessibleImageSampleBook_v2.0.3.epub":
   Corrupted EPUB ZIP header.

FATAL (PKG-008) FATAL_preposition "AccessibleImageSampleBook_v2.0.3.epub/AccessibleImageSampleBook_v2.0.3.epub":
   Unable to read file 'error in opening zip file'.

---------------------------------------------------

epubcheck finished with warnings or errors!

OxygenXML won't even attempt to open the file.

Please let me know when you post a new and working file?

Thanks very much!

Best,
Jean

**Comment by jstallent** [comment]
Apparently my computer decided it need to add a Thumbs.db file when it created the 2.0.3 version. I have removed that in version 2.0.4, and it should be fine now. Goes to show I should test files before uploading them...

**Comment by jeankaplansky** [comment]
Aha! Thanks!
